// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyCgapGy4D9ILiBMTj-7KKzv8zcPQ6gs',
    appId: '1:845251569451:web:0ae26f0aa9333bacb8476e',
    messagingSenderId: '845251569451',
    projectId: 'gracegrid-c7367',
    authDomain: 'gracegrid-c7367.firebaseapp.com',
    storageBucket: 'gracegrid-c7367.firebasestorage.app',
    measurementId: 'G-WMFX9V4W7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaxleC8ksuCxKV7Ov6PM6Cdaz7RNodHwg',
    appId: '1:845251569451:android:0aa76d7b441566f4b8476e',
    messagingSenderId: '845251569451',
    projectId: 'gracegrid-c7367',
    storageBucket: 'gracegrid-c7367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVkXYqfqoAGuk5OwKH7HMfoEjPZYRy1GM',
    appId: '1:845251569451:ios:a0a7b5ce486123d2b8476e',
    messagingSenderId: '845251569451',
    projectId: 'gracegrid-c7367',
    storageBucket: 'gracegrid-c7367.firebasestorage.app',
    iosBundleId: 'com.example.graceGrid',
  );
}
